name: Pull Request validation

on: [pull_request]


jobs:
  fullstack1-contracts-ci:
    name: Run fullstack1-contracts validation
    uses: ./.github/workflows/fullstack1-contracts-ci.yaml

  fullstack1-frontend-ci:
    name: Run fullstack1-frontend validation
    uses: ./.github/workflows/fullstack1-frontend-ci.yaml

